version: '3.7'

services:
  webserver:
    hostname: webserver
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - backup:/usr/share/nginx/html
    networks:
      priv-eth-net:

  netstats:
    hostname: netstats
    environment:
      - WS_SECRET=${ETHNET_PASSWORD}
    image: kamael/eth-netstats
    ports:
      - "3000:3000"
    networks:
      priv-eth-net:

  eth-explorer:
    hostname: eth-explorer
    environment:
      - APP_NODE_URL=http://161.35.23.208:8545
    image: alethio/ethereum-lite-explorer
    ports:
      - "8090:80"
    networks:
      priv-eth-net:

  bootnode:
    hostname: bootnode
    env_file:
      - .env
    image: geth-client
    build:
      context: .
      args:
        - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
    command:
      --nodekeyhex="b0ac22adcad37213c7c565810a50f1772291e7b0ce53fb73e7ec2a3c75bc13b5"
      --nodiscover
      --ipcdisable
      --networkid=${NETWORK_ID}
      --ethstats boot-node:${ETHNET_PASSWORD}@netstats:3000
    networks:
      priv-eth-net:

  rpc-endpoint:
    hostname: rpc-endpoint
    env_file:
      - .env
    image: geth-client
    depends_on:
      - bootnode
    command:
      --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@bootnode:30303"
      --allow-insecure-unlock
      --http
      --http.addr="0.0.0.0"
      --http.port=8545
      --http.api="eth,web3,net,admin,personal,miner,txpool,rpc"
      --http.corsdomain="*"
      --networkid=${NETWORK_ID}
      --ethstats interface-node:${ETHNET_PASSWORD}@netstats:3000
    ports:
      - "8545:8545"
    networks:
      priv-eth-net:

  miner1:
    hostname: miner-1
    env_file:
      - .env
    image: geth-client
    depends_on:
      - bootnode
    command:
      --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@bootnode:30303"
      --mine
      --miner.threads=1
      --networkid=${NETWORK_ID}
      --ethstats miner-1:${ETHNET_PASSWORD}@netstats:3000
    networks:
      priv-eth-net:

  miner2:
    hostname: miner-2
    env_file:
      - .env
    image: geth-client
    depends_on:
      - bootnode
    command:
      --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@bootnode:30303"
      --mine
      --miner.threads=1
      --networkid=${NETWORK_ID}
      --ethstats miner-2:${ETHNET_PASSWORD}@netstats:3000
    networks:
      priv-eth-net:

  miner3:
    hostname: miner-3
    env_file:
      - .env
    image: geth-client
    depends_on:
      - bootnode
    command:
      --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@bootnode:30303"
      --mine
      --miner.threads=1
      --networkid=${NETWORK_ID}
      --ethstats miner-3:${ETHNET_PASSWORD}@netstats:3000
    networks:
      priv-eth-net:

  miner4:
    hostname: miner-4
    env_file:
      - .env
    image: geth-client
    depends_on:
      - bootnode
    command:
      --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@bootnode:30303"
      --mine
      --miner.threads=1
      --networkid=${NETWORK_ID}
      --ethstats miner-4:${ETHNET_PASSWORD}@netstats:3000
    networks:
      priv-eth-net:

networks:
  priv-eth-net:
    driver: bridge
    ipam:
      config:
      - subnet: ${SUBNET_IP}

volumes:
  backup:
